/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aes.utility;

/**
 *
 * @author Michael.Goetz
 */
public class Tool {
   
    public static int XOR(int a, int b){
        return a ^ b;
    }
    
    public static int ByteSum(int a, int b, int c, int d){
        int x = a + b;
        if(x > 255)
            x = x - 255;
        
        int y = x + c;
        if(y > 255)
            y = y - 255;
        
        int z = y + d;
        if(z > 255)
            z = z - 255;
        
        return z;
    }
    
    public static void printArray(int[] array){
        for(int i = 0; i < array.length; i++){
            System.out.println("i=" + i + " , val= " + array[i]);
        }
    }
    
    
    public static int sbox(int input){
        
        switch(input){
            case 0: 
                return 0x63;
            case 1: 
                return 0x7C;
            case 2: 
                return 0x77;
            case 3:
                return 0x7B;
            case 4:
                return 0xF2;
            case 5:
                return 0x6B;
            case 6:
                return 0x6F;
            case 7:
                return 0xC5;
            case 8:
                return 0x30;
            case 9:
                return 0x01;
            case 10:
                return 0x67;
            case 11:
                return 0x2B;
            case 12:
                return 0xFE;
            case 13:
                return 0xD7;
            case 14:
                return 0xAB;
            case 15:
                return 0x76;
            case 16:
                return 0xCA;
            case 17:
                return 0x82;
            case 18:
                return 0xC9;
            case 19:
                return 0x7D;
            case 20:
                return 0xFA;
            case 21:
                return 0x59;
            case 22:
                return 0x47;
            case 23:
                return 0xF0;
            case 24:
                return 0xAD;
            case 25:
                return 0xD4;
            case 26:
                return 0xA2;
            case 27:
                return 0xAF;
            case 28:
                return 0x9C;
            case 29:
                return 0xA4;
            case 30:
                return 0x72;
            case 31:
                return 0xC0;
            case 32:
                return 0xB7;
            case 33:
                return 0xFD;
            case 34:
                return 0x93;
            case 35:
                return 0x26;
            case 36:
                return 0x36;
            case 37:
                return 0x3F;
            case 38:
                return 0xF7;
            case 39:
                return 0xCC;
            case 40:
                return 0x34;
            case 41:
                return 0xA5;
            case 42:
                return 0xE5;
            case 43:
                return 0xF1;
            case 44:
                return 0x71;
            case 45:
                return 0xD8;
            case 46:
                return 0x31;
            case 47:
                return 0x15;
            case 48:
                return 0x04;
            case 49:
                return 0xC7;
            case 50:
                return 0x23;
            case 51:
                return 0xC3;
            case 52:
                return 0x18;
            case 53:
                return 0x96;
            case 54:
                return 0x05;
            case 55:
                return 0x9A;
            case 56:
                return 0x07;
            case 57:
                return 0x12;
            case 58:
                return 0x80;
            case 59:
                return 0xE2;
            case 60:
                return 0xEB;
            case 61:
                return 0x27;
            case 62:
                return 0xB2;
            case 63:
                return 0x75;
            case 64:
                return 0x09;
            case 65:
                return 0x83;
            case 66:
                return 0x2C;
            case 67:
                return 0x1A;
            case 68:
                return 0x1B;
            case 69:
                return 0x6E;
            case 70:
                return 0x5A;
            case 71:
                return 0xA0;
            case 72:
                return 0x52;
            case 73:
                return 0x3B;
            case 74:
                return 0xD6;
            case 75:
                return 0xB3;
            case 76:
                return 0x29;
            case 77:
                return 0xE3;
            case 78:
                return 0x2F;
            case 79:
                return 0x84;
            case 80:
                return 0x53;
            case 81:
                return 0xD1;
            case 82:
                return 0x00;
            case 83:
                return 0xED;
            case 84:
                return 0x20;
            case 85:
                return 0xFC;
            case 86:
                return 0xB1;
            case 87:
                return 0x5B;
            case 88:
                return 0x6A;
            case 89:
                return 0xCB;
            case 90:
                return 0xBE;
            case 91:
                return 0x39;
            case 92:
                return 0x4A;
            case 93:
                return 0x4C;
            case 94:
                return 0x58;
            case 95:
                return 0xCF;
            case 96:
                return 0xD0;
            case 97:
                return 0xEF;
            case 98:
                return 0xAA;
            case 99:
                return 0xFB;
            case 100:
                return 0x43;
            case 101:
                return 0x4D;
            case 102:
                return 0x33;
            case 103:
                return 0x85;
            case 104:
                return 0x45;
            case 105:
                return 0xF9;
            case 106:
                return 0x02;
            case 107:
                return 0x7F;
            case 108:
                return 0x50;
            case 109:
                return 0x3C;
            case 110:
                return 0x9F;
            case 111:
                return 0xA8;
            case 112:
                return 0x51;
            case 113:
                return 0xA3;
            case 114:
                return 0x40;
            case 115:
                return 0x8F;
            case 116:
                return 0x92;
            case 117:
                return 0x9D;
            case 118:
                return 0x38;
            case 119:
                return 0xF5;
            case 120:
                return 0xBC;
            case 121:
                return 0xB6;
            case 122:
                return 0xDA;
            case 123:
                return 0x21;
            case 124:
                return 0x10;
            case 125:
                return 0xFF;
            case 126:
                return 0xF3;
            case 127:
                return 0xD2;
            case 128:
                return 0xCD;
            case 129:
                return 0x0C;
            case 130:
                return 0x13;
            case 131:
                return 0xEC;
            case 132:
                return 0x5F;
            case 133:
                return 0x97;
            case 134:
                return 0x44;
            case 135:
                return 0x17;
            case 136:
                return 0xC4;
            case 137:
                return 0xA7;
            case 138:
                return 0x7E;
            case 139:
                return 0x3D;
            case 140:
                return 0x64;
            case 141:
                return 0x5D;
            case 142:
                return 0x19;
            case 143:
                return 0x73;
            case 144:
                return 0x60;
            case 145:
                return 0x81;
            case 146: 
                return 0x4F;
            case 147:
                return 0xDC;
            case 148: 
                return 0x22;
            case 149:
                return 0x2A;
            case 150:
                return 0x90;
            case 151:
                return 0x88;
            case 152:
                return 0x46;
            case 153:
                return 0xEE;
            case 154:
                return 0xB8;
            case 155:
                return 0x14;
            case 156:
                return 0xDE;
            case 157:
                return 0x5E;
            case 158:
                return 0x0B;
            case 159:
                return 0xDB;
            case 160:
                return 0xE0;
            case 161:
                return 0x32;
            case 162:
                return 0x3A;
            case 163:
                return 0x0A;
            case 164:
                return 0x49;
            case 165:
                return 0x06;
            case 166:
                return 0x24;
            case 167:
                return 0x5C;
            case 168:
                return 0xC2;
            case 169:
                return 0xD3;
            case 170:
                return 0xAC;
            case 171:
                return 0x62;
            case 172:
                return 0x91;
            case 173:
                return 0x95;
            case 174:
                return 0xE4;
            case 175:
                return 0x79;
            case 176:
                return 0xE7;
            case 177:
                return 0xC8;
            case 178:
                return 0x37;
            case 179:
                return 0x6D;
            case 180:
                return 0x8D;
            case 181:
                return 0xD5;
            case 182:
                return 0x4E;
            case 183:
                return 0xA9;
            case 184:
                return 0x6C;
            case 185:
                return 0x56;
            case 186:
                return 0xF4;
            case 187:
                return 0xEA;
            case 188:
                return 0x65;
            case 189:
                return 0x7A;
            case 190:
                return 0xAE;
            case 191:
                return 0x08;
            case 192:
                return 0xBA;
            case 193:
                return 0x78;
            case 194:
                return 0x25;
            case 195:
                return 0x2E;
            case 196:
                return 0x1C;
            case 197:
                return 0xA6;
            case 198:
                return 0xB4;
            case 199:
                return 0xC6;
            case 200:
                return 0xE8;
            case 201:
                return 0xDD;
            case 202:
                return 0x74;
            case 203:
                return 0x1F;
            case 204:
                return 0x4B;
            case 205:
                return 0xBD;
            case 206:
                return 0x8B;
            case 207:
                return 0x8A;
            case 208:
                return 0x70;
            case 209:
                return 0x3E;
            case 210:
                return 0xB5;
            case 211:
                return 0x66;
            case 212:
                return 0x48;
            case 213:
                return 0x03;
            case 214:
                return 0xF6;
            case 215:
                return 0x0E;
            case 216:
                return 0x61;
            case 217:
                return 0x35;
            case 218:
                return 0x57;
            case 219:
                return 0xB9;
            case 220:
                return 0x86;
            case 221:
                return 0xC1;
            case 222:
                return 0x1D;
            case 223:
                return 0x9E;
            case 224:
                return 0xE1;
            case 225:
                return 0xF8;
            case 226:
                return 0x98;
            case 227:
                return 0x11;
            case 228:
                return 0x69;
            case 229:
                return 0xD9;
            case 230:
                return 0x8E;
            case 231:
                return 0x94;
            case 232:
                return 0x9B;
            case 233:
                return 0x1E;
            case 234:
                return 0x87;
            case 235:
                return 0xE9;
            case 236:
                return 0xCE;
            case 237:
                return 0x55;
            case 238:
                return 0x28;
            case 239:
                return 0xDF;
            case 240:
                return 0x8C;
            case 241:
                return 0xA1;
            case 242:
                return 0x89;
            case 243:
                return 0x0D;
            case 244:
                return 0xBF;
            case 245:
                return 0xE6;
            case 246:
                return 0x42;
            case 247:
                return 0x68;
            case 248:
                return 0x41;
            case 249:
                return 0x99;
            case 250:
                return 0x2D;
            case 251:
                return 0x0F;
            case 252:
                return 0xB0;
            case 253:
                return 0x54;
            case 254:
                return 0xBB;
            case 255:
                return 0x16;
                
            default:
                System.out.println("sbox input error: " + input );
                break;
        }
        return -1;
    }
    
    public static int roundConstant(int roundNumber){
        switch(roundNumber){
            case 1:
                return 0x01;
            case 2:
                return 0x02;
            case 3: 
                return 0x04;
            case 4: 
                return 0x08;
            case 5:
                return 0x10;
            case 6: 
                return 0x20;
            case 7:
                return 0x40;
            case 8: 
                return 0x80;
            case 9:
                return 0x1B;
            case 10:
                return 0x36;
            default:
                System.out.println("something broken in RC method...");
                return 0x00;
        }
    }
}
